parameters:



services:
    #Controllers
    oni_travel_port_auth_controller:
        class: Oni\TravelPortBundle\Co
        factory: [ '@oni_travel_port_auth_controller_factory',  getService]
        arguments:
                - '@service_container'
    oni_travel_port_index_controller:
        class: Oni\TravelPortBundle\Controller\Front\IndexController
        factory: [ '@oni_travel_port_index_controller_factory',  getService]
        arguments:
                - '@service_container'
    oni_travel_port_hotel_search_controller:
        class: Oni\TravelPortBundle\Controller\Front\HotelSearchController
        factory: [ '@oni_hotel_search_controller_factory',  getService ]
        arguments:
                - '@service_container'
    oni_travel_port_account_controller:
        class: Oni\TravelPortBundle\Controller\Front\AccountController
        factory: [ '@oni_travel_port_account_controller_factory',  getService]
        arguments:
                - '@service_container'
    oni_travel_port_account_controller:
        class: Oni\TravelPortBundle\Controller\Front\AccountController
        factory: [ '@oni_hotel_search_controller_factory',  getService ]
        arguments:
                - '@service_container'
    #Forms
    oni_travel_port_hotel_search_form:
        class: Oni\TravelPortBundle\Form\Front\HotelSearchForm
        factory: [ '@oni_travel_port_hotel_search_factory', getService ]
        arguments:
            - '@service_container'
        tags:
            - { name: form.type, alias: oni_hotel_search }

