parameters:
    oni_travel_connect_auth_controller_class: Oni\TravelPortBundle\Controller\FrontEnd\AuthController
    oni_travel_connect_hotel_search_controller_class: Oni\TravelPortBundle\Controller\FrontEnd\HotelSearchController
    oni_travel_connect_index_controller_class: Oni\TravelPortBundle\Controller\FrontEnd\IndexController
    oni_travel_connect_account_controller_class: Oni\TravelPortBundle\Controller\FrontEnd\AccountController


services:
    oni_travel_connect_auth_controller_class:
        class: '%oni_travel_connect_auth_controller_class%'
    oni_travel_connect_auth_controller:
        class: '%oni_travel_connect_auth_controller_class%'
        factory: [ '@oni_controller_factory',  getController]
        arguments:
                - '@oni_travel_connect_auth_controller_class'
    oni_travel_connect_index_controller_class:
            class: "%oni_travel_connect_index_controller_class%"
    oni_travel_connect_index_controller:
            class: "%oni_travel_connect_index_controller_class%"
            factory: [ '@oni_controller_factory',  getController]
            arguments:
                    - '@oni_travel_connect_index_controller_class'
    oni_travel_connect_hotel_search_controller_class:
            class: "%oni_travel_connect_hotel_search_controller_class%"
    oni_travel_connect_hotel_search_controller:
        class: "%oni_travel_connect_hotel_search_controller_class%"
        factory: [ '@oni_controller_factory',  getController]
        arguments:
                - '@oni_travel_connect_hotel_search_controller_class'
    oni_travel_connect_account_controller_class:
            class: "%oni_travel_connect_account_controller_class%"
    oni_travel_connect_account_controller:
        class: "%oni_travel_connect_account_controller_class%"
        factory: [ '@oni_controller_factory',  getController]
        arguments:
                - '@oni_travel_connect_account_controller_class'
