
oni_travel_port_index:
    path:     /admin/travel-connect/users
    defaults: { _controller: oni_travel_port_user_controller:indexAction }

oni_travel_port_add:
    path:     /admin/travel-connect/user/add
    defaults: { _controller: oni_travel_port_user_controller:addAction }

oni_travel_port_edit:
    path:     /admin/travel-connect/user/edit/{id}
    defaults: { _controller: oni_travel_port_user_controller:editAction }

#Front End Routes

oni_travel_port_login:
    path: /travelportal/login
    defaults:
        _controller: oni_travel_port_auth_controller:loginAction
oni_travel_port_home:
    path: /travelportal/
    defaults:
        _controller: oni_travel_port_index_controller:indexAction
oni_travel_port_check:
    path:      /travelportal/login_check
    defaults:
        _controller: oni_travel_port_auth_controller:loginCheck
oni_travel_port_logout:
    path:      /travelportal/logout
    defaults:
        _controller: oni_travel_port_auth_controller:logout

oni_travel_port_hotel_search:
    path:      /travelportal/hotel-search
    defaults:
        _controller: oni_travel_port_hotel_search_controller:indexAction

oni_travel_port_account:
    path:      /travelportal/account
    defaults:
        _controller: oni_travel_port_account_controller:indexAction
