services:
    oni_travel_port_user:
        class: Oni\TravelPortBundle\Entity\User
    oni_travel_port_user_groups:
        class: Oni\TravelPortBundle\Entity\UserGroups
    oni_travel_port_user_repository:
        class: Oni\TravelPortBundle\Entity\Repository\UsersRepository
        factory: [ '@doctrine.orm.default_entity_manager',  getRepository]
        arguments:
                - Oni\TravelPortBundle\Entity\User
    oni_travel_port_twig_helper:
        class: Oni\TravelPortBundle\Twig\TravelPortTwigHelper
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
    oni_travel_port_user_provider:
        class: Oni\TravelPortBundle\Security\UserProvider
        arguments: ["@oni_travel_port_user_service"]
    oni_travel_port_user_controller:
        class: Oni\TravelPortBundle\Controller\UserController
        factory: [ '@oni_travel_port_user_controller_factory',  getService]
        arguments:
                - '@service_container'
    oni_travel_port_user_service:
        class: Oni\TravelPortBundle\Services\UserService
        factory: [ '@oni_travel_port_user_service_factory', getService]
        arguments:
            - '@service_container'




