<?php

namespace Oni\TravelConnectBundle\Repository;

/**
 * CompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesRepository extends \Doctrine\ORM\EntityRepository
{
}
