<?php

namespace Oni\TravelPortBundle\Entity\Repository;

/**
 * TravelPortUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAllUsersWithFieldTitles($offset = 2, $maxResults = 20){

		$return = array(
			'results' => array(),
			'titles' => array()
		);

		$keys = array(
			'id' => 'pc.id',
			//translation ids as keys
			'name' => 'pc.productCategoryName',
			'product_bundle.category.url' => 'pc.productCategoryUrl'
		);

		$qb = $this->getEntityManager()->createQueryBuilder()
		           ->select($keys)
		           ->from($this->table, 'pc')
			//->setFirstResult($offset)
			//->setMaxResults($maxResults)
			       ->where('pc.lvl != 0');

		$query = $qb->getQuery();

		$query->setHint(
			\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
			'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
		);

		$query->setHint(\Gedmo\Translatable\TranslatableListener::HINT_FALLBACK, 1);

		//$results = new Paginator($query, $fetchJoinCollection = true);

		$results = $query->getResult();

		$return['results'] = $results;
		$return['titles'] = $keys;


		return $return;

	}

}
